version: "3.1"

networks:
    laravel-net:
        name: laravel
        driver: bridge

services:
    db:
        image: mysql:8
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: example
            MYSQL_PASSWORD: secret2

    phpmyadmin:
        build:
            context: ./docker/phpMyAdmin
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8180:80
        depends_on:
            - db
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=1G
        networks:
            - laravel-net
